name: Build to AWS ECR

on: push

jobs:
  login-to-aws:
     runs-on: ubuntu-latest
     steps:

     - name: Code Checkout
       uses: actions/checkout@v4

     - name: Login to AWS
       uses: aws-actions/configure-aws-credentials@v4
       with:
         aws-access-key-id: ${{ secrets.ACCESS_KEY }}
         aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}
         aws-region: ${{ secrets.REGION }}
